cfpb/development

- .eslintrc
ESLint file cleanup.
- Adds `align: value` property to `key-spacing` rule, which left-aligns values of properties in an object literal declaration.
- Generalizes comments to describe the rule not the state of the rule.
- @ascott1
- @wpears 
- @mistergone
> Updates eslint

- README.md
- browser-checklist.md
This adds the browser testing checklist from the Capital Framework docs. Once we all agree on this document, I'll update the docs to point to it so that we have a single source of truth.
> add a browser testing checklist

- .eslintrc
- CHANGELOG.md
Changed it from 4 spaces to 2 spaces.
Review: @Scotchester @ascott1
> Fix tab width in .eslintrc

- code-reviews.md
I noticed Scott's changes in #43 wasn't showing up in the guide. This fixes that and should keep the code review guide in line with the latest changes to the Pull Request template.
> Fix PR Template Link

- .eslintrc
Updates ESLint config for ESLint 0.21.0.
- Lists the JS parser used as `espree`.
- Adds additional environments supported by ESLint. `browser`, `node`, `amd`, and `phantomjs` are `true` to enable global values for `console`, `require`, etc., but everything else is off. Individual projects might want to set `jquery: true` here, but I'd err on the side of discouraging global jQuery, so set it to `false`.
- Adds `no-dupe-args` rule and enforces it.
- Adds `no-duplicate-case` and enforces it.
- Adds `dot-location` and enforces it on the property line. This means the period goes on it's own line when chaining methods. E.g.:
```
// yes
something
.that()
.does()
.something();
// no
something.
not().
this().
way();
```
- Adds `@todo` to the `no-warning-comments` rule to pick up TODO comments in …
> Updates ESLint config to 0.21.0

- .eslintrc
Relaxes key-spacing rule to warning for consistency with space-in-parens and space-in-bracket settings.
- Changes key-spacing to warning.
- Removes unneeded newline.
- Misalignment of property values in an object literal should throw a warning, not an error, and thus won't break a build.
- @ascott1 
- @wpears 
- @mistergone
> Relaxes key-spacing rule

- .eslintrc
Relaxes complexity setting to 4 to allow for switch statements and certain if statement structures.
A cyclomatic complexity of 3 allows:
```js
if (arg1 === true) { … }
else if (arg2 === true { … }
else { … }
```
However, there are circumstances where it's not desirable to have a catch-all else block at the end, and instead the following is needed:
```js
if (arg1 === true) { … }
else if (arg2 === true) { … }
else if (arg3 === true) { … }
```
This has a cyclomatic complexity of 4, presumably because there's an implicit ending else statement that could be present. This also applies to `switch` statements, which have an implicit "default" block that will increment the complexity by one.
This PR proposes raising the cyclomatic complexity threshold to 4 to allow for three route if/else blocks …
> Relaxes complexity setting to 4

- .eslintrc
- CHANGELOG.md
Implements the fix @sephcoster found today. I just ran into the same bug while working on the generator.
- Adds jQuery to list of allowed globals in `.eslintrc`.
- Updates changelog appropriately.
- @sephcoster 
- @jimmynotjim 
- Setting it to `false` checks that your code doesn't overwrite `$`.
> Add jQuery to list of allowed globals

- javascript-modules-commonjs.md
- javascript.md
I thought it might be helpful to add some guidance on structuring commonJS modules so I threw this doc together with the best practices I'm familiar with. What do you think?
- Adds commonjs module structure guidance.
- Changes UpperCamelCase to PascalCase.
- Adds note about conventions of dollar sign prefixing jQuery references.
- @ascott1 
- @wpears 
- @mistergone
> Adds commonjs module structure guidance

- .eslintrc
- CHANGELOG.md
Updates ESLint settings to conform with version 0.24.0.
- Adds `worker`, `mongo`, `applescript` variables to `env`.
- Adds and enforces `no-empty-character-class` rule.
- Adds and enforces `no-unexpected-multiline` rule.
- Adds and warns `accessor-pairs` rule.
- Adds and doesn't enforce `no-param-reassign` rule.
- Adds and warns `array-bracket-spacing` rule.
- Adds and warns `computed-property-spacing` rule.
- Adds and warns `lines-around-comment` rule.
- Adds and enforces `object-curly-spacing` rule.
- Adds and enforces `constructor-super` rule.
- Adds and enforces `no-this-before-super` rule.
- Adds and enforces `prefer-const` rule.
- Removes deprecated `no-wrap-func` rule.
- Removes deprecated `space-in-brackets` rule.
- Removes deprecated `spaced-line-comment` rule.
- Alphabetize …
> Updates ESLint settings to conform with version 0.24.0

- css.md
Let me know how this reads.
There's one property not shown here that I wonder about which group it belongs in: `content`. This seems like a significant/non-decorative enough property to not go in the "other" bucket. Should it be listed in the first group?
Any other ambiguous properties anyone else wonders about?
Closes #59
> First crack at property order reasoning

- build.md
- closes #66 
Updated build guide for our latest processes
- links to sample gruntfile in generator-cf
- links to sample setup.sh in generator-cf
- None
- updates name of bootstrap script to setup.sh
- @cfpb/front-end-team-admin 
- link to setup.sh won't actually work till that PR is merged, but figured it was easier to just set it once
> Updated build guide for our latest processes

- code-reviews.md
- pr-template.md
Add our PR submitter checklist to the Pull Request template so we can easily check off the requirements of each PR when we submit it.
- PR checklist for submitter
- added a link in our Code Review standards to bookmarklet code for checklists reviewers and for submitters in Gists (should we add these to the repo?)
- removed placeholder text from the PR template, so it's easier to copy, paste, update.
- changed "Notes" to "Todos" since that's how I've been using it. I put any generic "notes" in the intro paragraph. Todos is for upcoming related PRs, or tasks to finish in the PR.
- save bookmarklet code to your browser bar, try to make a PR with it.
- @ascott1
> Add PR submitter checklist to Pull Request template

- README.md
I think the quote is fantastic. But since some folks might not be familiar with where it comes from, we should add a link crediting idiomatic.js.
- Added line crediting idiomatic.js for quote on our standard guidelines
> Add credit for quote from idiomatic.js

- .eslintrc
Updates ESLint config for compatibility with ESLint 1.0.0.
- Adds `restParams: true` to ESLint config, to allow use of ...rest syntax.
- Adds `experimentalObjectRestSpread: false` to ESLint config.
- Adds `qunit: false` to environments.
- Adds `serviceworker: true` to environments to support use of serviceworker API.
- Adds `embertest: false` to environments.
- Adds new rules: `no-implicit-coercion`, `no-invalid-this`, `no-param-reassign`, `no-useless-call`, `callback-return`, `id-length`, `id-match`, `arrow-parens`, `arrow-spacing`, `no-class-assign`, `no-const-assign`, `prefer-spread`, `prefer-reflect`, `require-yield`.
- Removed deprecated `no-reserved-keys` rule.
- Changes `phantomjs` environment to `false` since this should be overridden if needed in a test directory eslintrc file.
- …
> Update ESLint config to 1.0.0. compatibility

- .eslintrc
With new `indent` option `VariableDeclarator` set to `1`, ESLint was requiring that multiline variable declarations have their additional lines be indented by only 2 spaces. This change will allow us to continue to align the variable names (at 4 spaces for `var` and `let` declarations, and 6 spaces for `const` declarations).
- @ascott1
> Tweak indent rules for multi-line var declarations

- CHANGELOG.md
- README.md
- package.json
This adds any missing links to the TOC in the README, alphabetizes those links, adds a note about npm, and bumps this to 1.1.0 as there are several unpublished changes not in npm.
@cfpb/front-end-team-admin
> Update README with full list of links

- .eslintrc
The `key-spacing` rule can get a bit funky when properties in an object have other objects as values, reading to less readability than before the rule is applied! It also can cause issues with exceeding the max line length when it otherwise wouldn't if alignment was not happening on the property values. This tweak makes property keys have *at least* 1 space after the colon, allowing the values to aligned when it makes sense, or not when it doesn't.
- @ascott1  
- @wpears 
- @mistergone
> Relax key-spacing slightly

- .eslintrc
- CHANGELOG.md
Currently our rule is to only use quotes when absolutely necessary. This can produce some funky results, like: 
```javascript
{
rule:               false
'hyphenated-rule':  true
}
```
This updates the rule to be consistent within each object, which seems reasonable to me.
Thoughts?
@anselmbradford 
@wpears
> Update quote-props to "consistent as needed"

- .github/PULL_REQUEST_TEMPLATE.md
#Somewhere along the line of updates to this template, we lost the link to view a PR without whitespace changes.
- A link to view the created PR without whitespace changes.
- Standard PR view with lots of whitespace changes: https://[GHE]/CCDB4/CCDB-content/pull/54
- Preview that PR without the whitespace changes: https://[GHE]/CCDB4/CCDB-content/pull/54?w=0
- @jimmynotjim
> Restore link to review PR wo whitespace changes

- .eslintrc
- Updates eslintrc for compatibility with ESLint to `2.13.1`
- Adds additional environments settings.
- Adds `prefer-spread`, `prefer-rest-params`, `no-magic-numbers`, `no-restricted-imports`, `init-declarations`, `max-lines`, `object-curly-newline`, `newline-before-return`, `no-prototype-builtins`, and `newline-per-chained-call` rules, but does not enforce them.
- Enforces `no-useless-constructor`, `array-callback-return`, `no-case-declarations`, `no-unused-labels`, `no-empty-function`, `no-extra-label`, `no-implicit-globals`, `no-self-assign`, `no-unmodified-loop-condition`, `no-empty-pattern`, `no-unsafe-finally`, `no-duplicate-imports`, `unicode-bom`, `no-useless-computed-key`, `no-useless-rename`, `rest-spread-spacing`, and `no-restricted-globals` rules.
- Warns on …
> Updates eslintrc for compatibility with ESLint to `2.13.1`

- .eslintrc
- CHANGELOG.md
- Updates ordering of rules to match ESLint docs.
- Adds new `line` and `block` sections to `spaced-comment` rule.
- Adds but doesn't enforce `multiline-ternary`.
- @Scotchester 
- @contolini 
- @wpears 
- @mistergone 
- Mostly moves code around and updates a code comment. Only one actual rule is updated.
> Updates eslintrc for compatibility with ESLint to `3.1.1`

- css.md
Following the discussion that recently arose in the Atomic Design channel, I propose changing our official CSS (or Less) indentation standard to four spaces.
- Most of our CSS codebase is already indenting at four spaces, so it'd be a smaller change to make the two-space code we have match the four-space code.
- I don't have data to back this up, just my impression from having seen a large proportion of the CSS we've written here over time, but I am pretty confident in this assertion. Feel free to prove me wrong.
- There's very little danger of long line lengths in CSS, so no need to save characters.
- Four-space indentation is our standard for HTML and Python, as well.
- @cfpb/front-end-team-admin
> Proposal: Change CSS indentation standard to four spaces

- code-reviews.md
This adds standards for code review assignment + deadlines for merging PR's.
- Recommends that a person creating a pull request assign a specific Github user to review the PR
- Recommends limiting reviewers to 1 person who will 👍  or 👎 
- Adds a 1 week deadline in which PRs can be self-merged if no feedback or comments are given.
- We are testing this out on Capital Framework over the next few weeks, check back to see how it went.
> Add deadline + assignment standards

- CHANGELOG.md
- atomic-design.md
Moving https://github.com/cfpb/capital-framework/issues/340 and the workshop slides to the standards so it's easier to discover and reference.
- Atomic Guide
- @KimberlyMunoz 
- @cfarm 
- @mistergone 
- @Scotchester
- @sebworks  
- @contolini 
- @virginiacc
- @sephcoster 
- @wpears 
- @ascott1 
- Flesh out details for each element type. I just copied the slides for the time being.
- Address layout rules from cfgov-refresh. I wanted to get the basic stuff down first.
> Added starter guide for atomic design

- .eslintrc
Updates `allowKeywords` to `true` to allow Promises. Promises use `catch` for errors, but setting `allowKeywords` to `false` means `.catch` cannot be used because it's a keyword from a try/catch block. With this update, codebases using this linting file can fully support promises.
Follows update in https://github.com/cfpb/cfgov-refresh/pull/2334
- Updates `allowKeywords` to `true`.
- @wpears 
- @ascott1 
- @Scotchester 
- @mistergone
> Updates `allowKeywords` to `true` to allow Promises

- README.md
- open-source-template.sh
This moves the open source project template script to this repo, as discussed in [open-source-project-template/pull/22](https://github.com/cfpb/open-source-project-template/pull/22#issuecomment-295805323)
> Add open source project template script

- CHANGELOG.md
- browser-checklist.md
- javascript.md
We haven't supported scripted interaction in IE8 since the relaunch. Documenting this fact here for future contributors and updating the browser checklist to match.
- @cfarm 
- @sebworks 
- @ascott1 
> Update standards to account for IE8

- guides/pypi.md
This commit fixes a slight error in the PyPI guide. The upload command should be `twine upload dist/*` not `twine upload dist/*.whl` to ensure that both the source and wheel files get uploaded to PyPI.
> Fix error in PyPI instructions

- .flake8
- .isort.cfg
- README.md
- standards/python.md
- tox.ini
This PR adds a sample flake8, isort, and tox configuration for Python linting and testing against Python 2 and Python 3. It also starts documenting these three topics in a [Python standards file](https://github.com/cfpb/development/blob/7c98e98ed3425ce20f1ed6f79684671dd77f6671/standards/python.md).
I'm looking to include all of this in a Django app boilerplate to be used next week, so I'd love thoughts and feedback on this. 
The isort configuration corresponds to [my proposal in cfgov-refresh](https://github.com/cfpb/cfgov-refresh/pull/3602), and whatever decision is made around it here I will reflect in that PR.
The flake8 configuration is based on cfgov-refresh as well.
> Add Python linting and version-testing standards

- guides/pypi.md
We should recommend the creation of universal wheels, as described at https://packaging.python.org/tutorials/distributing-packages/#wheels. This allows our wheels to be used with both Python 2 and 3.
> Specify creation of universal wheels

- .eslintrc
- `allowBlockStart` to `true` in eslint `lines-around-comment` rule.
> allowBlockStart to true in eslint lines-around-comment rule.

- guides/browser-support.md
Each project doesn't have a contributing.md browser support section, but this sets up the linkages to where those sections should be.
- Links to each project's contributing.md browser support section.
> Links to browser-support section of individual project contributing.md

- tools/browser-checklist.md
- Adds asterisk to IE9, which now doesn't need to support JS, per https://github.com/cfpb/cfgov-refresh/pull/3693
> Add optional-JS for IE9

- .eslintrc
Modifying `experimentalObjectRestSpread` because it's reached TC39 stage 4
- Modifying `experimentalObjectRestSpread` because it's reached TC39 stage 4 and thus is no longer experimental.  https://github.com/tc39/proposal-object-rest-spread
1.
-
-
> Modifying `experimentalObjectRestSpread` because it's reached TC39 stage 4

- standards/python.md
This PR adds a section to our Python standards about dependency specification in requirements.txt and setup.py files. 
The motivation for this is two-fold; first, the perpetual confusion around this in the Python world and the subsequent confusion this causes folks who just want to get their work done, and second discovering that we have some disparity in regard to this, along with some places where folks have tried to bridge the gap between requirements.txt and setup.py.
Hopefully this is succinctly helpful as it is, and it includes a link to a more in-depth discussion. Donald Stufft's article is [linked to by the pip documentation](https://pip.pypa.io/en/latest/user_guide/?highlight=Donald#requirements-files) for this same reason.
I've made no mention of pipenv here, as we don't really …
> Add section about python dependencies

- standards/javascript.md
This is a tiny change in preparation for further future standards updates to avoid whitespace diffs in that PR.
- Fix the line lengths
> Fix the js standard line lengths

- guides/browser-support.md
Add manual testing instructions to the browser support guide to help ensure developers are adhering to our list of supported browsers.
- Added instructions for localtunnel
- Added section for Saucelabs, needs content from @cfarm 
1. Follow the instructions to set up localtunnel on your machine.
- Add Saucelabs instructions.
> Add manual testing instructions

- README.md
- guides/accessibility.md
- guides/screen-reader-differences.md
Adds screen reader differences guide which I wrote to document research findings about Windows screen readers.
- new guide which talks about JAWS, NVDA, and VoiceOver and what the differences between each application mean for developers when writing code
- I am looking for editorial feedback and corrections but not accepting major edits/revisions. This guide has been read and reviewed in draft form by the accessibility remediation team. I post it here so it can serve as a reference for other developers outside that team, too.
> Screen reader differences

- .flake8
- standards/python.md
This adds W504, line break before binary operator to our example flake8 configuration. This was recently done in cfgov-refresh in https://github.com/cfpb/cfgov-refresh/pull/4608.
[PEP8 merely requires local consistency](https://legacy.python.org/dev/peps/pep-0008/#should-a-line-break-before-or-after-a-binary-operator) and doesn't preference particular line breaking around binary operators.
An alternative here is we can chose a particular style and enforce it across our code — we'd just need to decide what we want to do (I'd vote strongly in favor of Knuth-style). With this PR we're leaving line breaks around binary operators up to local context (which also makes sense to me given our codebase).
> Ignore W504, a sibling of W503

- README.md
- guides/unittesting-django-wagtail.md
- tox.ini
This PR adds documentation about how we write tests for Django and Wagtail and includes examples of common test patterns.
https://github.com/cfpb/development/blob/unittesting-django-wagtail/guides/unittesting-django-wagtail.md
> Add documentation about testing Django & Wagtail

- CHANGELOG.md
As the `CHANGELOG.md` file in this repository has gotten very out of date (at least until @niqjohnson's recent change in #187), we could consider deprecating it and relying instead on GitHub.com's history, as we do with cfgov-refresh.
This PR deprecates the use of `CHANGELOG.md` for tracking changes and replaces it with a placeholder file using the same style as the one in cfgov-refresh:
https://github.com/cfpb/cfgov-refresh/blob/master/CHANGELOG.md
> Deprecate CHANGELOG.md

- .github/PULL_REQUEST_TEMPLATE.md
This PR renames "development playbook" in the PR template to "CFPB development guidelines" for consistency with how this repo is named in its README and how we refer to it elsewhere.
> Rename "development playbook" link for consistency

- .gitignore
- README.md
- guides/installing-python.md
This change adds a new document describing how to install Python 2 and 3 using pyenv. This is intended to help standardize how we install and use multiple versions of Python so that we have as much consistency as possible.
This is based on work done by the backends on our PyFridays, including the initial heavy-lifting done by @hillaryj (this work is recorded in GHE at CFGOV/platform/wiki/Pyenv). This is submitted for review/testing/etc as a first-pass. 
Before we merge this in we'll probably want to update some of the documentation for our major projects ([*cough*](https://cfpb.github.io/cfgov-refresh/installation/)) to reference this and ensure that there are no conflicts between what they this tells you to do and our other documents.
But given that [cfgov-refresh tox and Travis now run …
> Installing python

- guides/unittesting-django-wagtail.md
[Django-Flags is deprecating bare dict `FLAGS` definitions](https://cfpb.github.io/django-flags/releasenotes/#41) and using these patterns as suggested will cause deprecation warnings. This PR changes those suggestions to the [supported two-tuple format](https://cfpb.github.io/django-flags/settings/#flags)
> Change FLAGS settings syntax suggestions

- README.md
The git-secrets documentation isn't linked from the README. This PR fixes that.
> Add git-secrets documentation to README.md

- tools/git-secrets-patterns/README.md
- tools/git-secrets-patterns/default.txt
This PR modifies our git-secrets instructions to exclude comments *and* newlines. 
It also removes the credit card regular expression. This regex was causing issues when excluding newlines (`grep: empty (sub)expression`, described in #196). It also does not match many formats of credit card numbers. I believe it's better to not have any cred card number matching at all than to rely on matching that will not match American Express cards and other formats. So I have removed it. We can work to craft a new one at a later date.
Closes #196.
> Resolve spacing and regular expression issues in git-secrets instructions and patterns

- guides/unittesting-django-wagtail.md
With the upgrade to Wagtail 2.3, we've decided that all links to Wagtail docs can now point to the `stable` version of the docs.
- Updated all the links to Wagtail docs to point to the `stable` version instead of the `1.13.4` version.
- Updated all the links to Wagtail docs to use `https` instead of `http`.
- Looks like a bunch of white space changes snuck in, too—thanks, VSCode.
1. Make sure the three updated links (L27, L343, L375) all work.
2. I guess also make sure none of the whitespace changes VSCode made break anything?
> Update links to Wagtail docs

- pyproject.toml
- standards/python.md
We've started using Black in [various](https://github.com/cfpb/django-flags) [projects](https://github.com/cfpb/retirement) and it has been helpful as we need to add linting to projects that predate our linting standards.
This change adds documentation about how we're using Black and clarifies that we've deviating from Black's preferences on line length (because we're all set up for our standard PEP8 79 char).
> Add Black to our Python standards

- guides/pypi.md
Now that we're no longer encouraging use of Python 2, should we remove mention of creating universal wheels here?
> Remove mention of universal wheels

- README.md
- guides/pipx.md
This change adds a document (based on one written by @Scotchester for docker-compose specifically) that describes installing, configuring, and using pipx for installing command-line Python tools.
> Add documentation for using pipx

- .isort.cfg
- tox.ini
This change updates the isort example config to remove the `not_skip` setting that was deprecated and removed in [isort 5.0](https://github.com/timothycrosley/isort/blob/5.0.0/CHANGELOG.md#500-penny---july-4-2020).
See some additional context in https://github.com/cfpb/cfgov-refresh/pull/5840.
> Update the isort example config

- guides/tracking-django-wagtail.md
- standards/python.md
In this change I have attempted to document the process we've undertaken to upgrade Django and Wagtail.
I've moved the supported-versions matrix from the Python standard doc and makes it more concrete to apply to Django and Wagtail and cf.gov and its satellites and libraries.
I've documented the approach we have been taking to feature detection and version testing, and the actual approach to keeping satellites, libraries, and cf.gov itself up-to-date.
It's a little bit ARID with the changes to the Python standards doc and tox, but that's intentional.
I would still like to add more links to GitHub Actions, once I revisit #206 and the GitHub Actions templates, but for now this is a starting point.
You can preview the changes here:
https://github.com/cfpb/development/blob/tracking-django-wagt …
> Add documentation for tracking changes to Django and Wagtail

- guides/browser-support.md
- guides/documentation.md
- guides/front-end-testing.md
- guides/installing-python.md
- guides/tracking-django-wagtail.md
- guides/unittesting-django-wagtail.md
- standards/css.md
- standards/python.md
This change updates our docs to point to github.com/cfpb/consumerfinance.gov instead of ot github.com/cfpb/cfgov-refresh.
> Rename cfgov-refresh to consumerfinance.gov
