README.md

This adds a rough overview of our standards and styles goals to the README.

overview of standards and styles process

---

markup.md

Move markup standards to Master

---

.eslintrc

This adds our recommended ESLint file.
- @wpears 
- @mistergone

add eslint file

---

CHANGELOG.md
README.md
javascript.md

This add's an initial JavaScript standard based on @bevacqua's [JS qualityGuide](https://github.com/bevacqua/js).
- @wpears 
- @mistergone

Add a JavaScript standard

---

README.md
css.md

This takes the work that @Scotchester and @cfarm did and adds a little bit of meat to it. It is still incomplete, but hopefully gives us a good starting point.
@Scotchester @cfarm

Introduce CSS standard

---

markup.md

Added a credit section to the markup guidelines. 
@jimmynotjim, can you take a look and see if I'm missing anything?

Adding Credits to Markup

---

CHANGELOG.md
README.md
build.md

This is a direct copy of some internal documentation. It could probably use some additional cleanup.

introduce build guidelines

---

code-reviews.md
pr-template.md

Adds a helpful review guide and PR template to help get us all on the same page and answer @cfarm  and @ascott1's question:
> What constitutes a good code review?
- Added review-guide.md
- Added pr-template.md
None
None
- @ascott1 
- @cfarm 
- et al. in front-end
None
- review guide is a collection of internal and external resources on code reviews
- PR template is one we have been using on FlapJack with good success
- closes #33

Adds review guide and PR template

---

pr-template.md

Not sure if this is the perfect place for it in the file, but what do you all think?

Add line to preview PR without whitespace changes

---

javascript.md

Edits the JS comments section in the playbook to fix formatting/grammar and adds section about JSDocs. 
- Creates comments section sub-sections and adds note about JSDocs.
- Discourages same-line comments.
- Proper grammar in comments.
- @ascott1 
- @wpears 
- @mistergone

Edits JS code comments block

---

css.md

This adds some guidelines to Less comments as discussed in #10.
@Scotchester, @jimmynotjim, @anselmbradford

Add Less comment guidelines

---

css.md

Adds example code to general practices. Fixes #60 
- Adds example code to `css.md`.
- @ascott1

Fixes #60 - adds example

---

browser-checklist.md

If any CFPBers are interested in the numbers, take a look at GHE/flapjack/Getting-started-with-Flapjack/issues/43
- Removes IE7 
- Adding Android 4.0
- @cfarm 
- @ascott1 
Closes #31

Updating Browser Checklist

---

build.md

Add gulp language to build page

---

.eslintrc

Fixes #92 
@ascott1 @Scotchester

Fixes #92 - removed erroneous comment

---

testing.md

Update 18f link to new pages endpoint

---

.github/ISSUE_TEMPLATE.md
.github/PULL_REQUEST_TEMPLATE.md

Updates the project w/ PR and Issue templates for Github
- Adds new Issue template
- Moves and renames existing PR template
- I have no idea
- @cfpb/front-end-team-admin 
- See https://help.github.com/articles/creating-a-pull-request-template-for-your-repository/

Updates the project w/ PR and Issue templates for Github

---

code-reviews.md

Herein, I add 2 cents worth of code review suggestions

Additional review suggestions

---

build.md

Fixes broken links to example files and clarifies a few things.
- @cfpb/front-end-team-admin 
- Would someone (probably @contolini) be willing to update the Node installation instructions to incorporate nvm?

Update build guidelines

---

CHANGELOG.md
code-reviews.md

Fixes #116.
- Added note about who should be assigned to review a PR. 
- @cfarm 
- @Scotchester 

Added note about who should be assigned to review a PR. 

---

README.md

This updates the repo description in the README to encompass the broader development team

update README description

---

README.md
api.md

This introduces draft API standards forked from [18F's guidelines](https://github.com/18F/api-standards) and adapted to be CFPB specific.
Please suggest edits or changes through comments or as a review. Once we've hit enough 👍 's that it feels like general consensus has been reached for an initial draft, I'll merge.

Introduce draft API standards

---

build.md

To help for folks seeking guidance on creating a new project front-end, let's make sure they know about the npm yeoman generator for creating node modules (not just about generator-cf).

add npm generator to worfklow recommendations

---

README.md
pypi.md

This commit includes a draft how-to document for publishing CFPB Python
packages to PyPI.
- New `pypi.md`.
- Link to `pypi.md` in the `README`.
- @rosskarchner @willbarton @ascott1

PyPI how-to

---

tools/browser-checklist.md

I _believe_ this is false advertising.

Drop Blackberry Bold from list of tested devices

---

.eslintrc

- Pull in latest ESLint 4 changes.

Update to ESLint 4 compatibility

---

guides/browser-support.md

Collected all our work from the browser support working group to create a guide on building cross-browser components.
- Added new browser support guide
- Read it, provide some feedback
- @cfpb/front-end-team-admin 
- I didn't include any references to the change management decisions, wasn't sure if that should live here or internally.

Browser support guide

---

.github/PULL_REQUEST_TEMPLATE.md

- Removes reviewer section, since that's built into GH now.

Updates pull request template to match cfgov-refresh

---

standards/javascript.md

Yet another small change in preparation for further future standards updates.
- Update all the code examples to use es6 variable and function formatting.

Update the JS Standard with es6 examples

---

README.md
guides/coding-at-cfpb.md

After a handful of discussions, here's the first pass at a "definition of done" document. It is framed as a series of steps throughout the lifecycle of a project to encourage developers to reference it from the get-go instead of only when their project is complete.
- Coding @ CFPB guide
1. Preview it at https://github.com/cfpb/development/blob/coding-at-cfpb/guides/coding-at-cfpb.md
- I'm open to any grammatical suggestions. It irks me a teeny bit that the verb tenses aren't consistent.

First pass at general coding guide

---

standards/javascript.md

The content of the guide has not kept up with our everyday code
practices. This update brings the guide up to where we currently are as
a team.
- Updated to include latest guidance on `use strict`
- Updated to enforce 2 space tab rules.
- Updated to include string and template rules.
- Updated to include the drop in interactive scripting to IE 9.

Update the guide to latest standards

---

README.md
guides/documentation.md

Adds new guide for developers about writing documentation.
Ping @niqjohnson who I can't request as a reviewer here.

Draft documentation guidelines

---

README.md

We came up with these as part of the Browser Support Working Group. Rather than keeping them buried in a Google Doc somewhere, I'd like to place them somewhere prominent for future reference.
I thought about replacing the existing "Core Values" since, a) I don't know where those came from and if current team had much input and b) these new values were created as a group by FEWDs, which I think might better represent our culture. But BEWDs had no input in the new values so that's the main reason I held back from replacing. Thoughts on that?

Add FEWD values to readme

---

guides/documentation.md

This PR adds a few additional recommendations to the documentation guide.
These recommendations come from the learnings from Project Boost, a CFPB project review conducted back in 2016 by @amymok (we miss you!) and @marteki.

Add additional documentation recommendations

---

README.md
guides/installing-python.md
guides/unittesting-django-wagtail.md
standards/python.md

Update documentation for Python 3.6
- Python 3.6
- Replace Python 2.7 with 3.6

Update documentation for Python 3.6
